# Generated by Django 4.2.4 on 2023-09-11 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 11, 16, 51, 23, 977873, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True)),
                ('eat_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=500)),
                ('dinner', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 9, 11, 16, 51, 23, 977873, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
