# Generated by Django 4.1.3 on 2022-12-11 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 13, 41, 5, 730970, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=True)),
                ('eat_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=500)),
                ('dinner', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 13, 41, 5, 731970, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
