# Generated by Django 4.1.3 on 2022-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0002_congression_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='congression',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='followers', to='iot_app.user'),
        ),
    ]
