# Generated by Django 4.1.3 on 2022-11-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0003_user_alter_congression_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congression',
            name='follower',
        ),
        migrations.AddField(
            model_name='congression',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to='iot_app.user'),
        ),
        migrations.AddField(
            model_name='congression',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
